const fs = require('fs');
const path = require('path');

const root = __dirname;
const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });
const source = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const banner = '<!-- generated by npm run build; data is served by the Go CLI -->\n';
fs.writeFileSync(path.join(dist, 'index.html'), banner + source);
